/**
 * Nile Services Agency - Portfolio / Case Studies Data
 * Features actual projects delivered by Nile Africa / Winner Oyekunle
 */

const portfolioData = [
  {
    id: "port-zesta-juice",
    title: "Zesta Citrus Burst",
    category: "packaging",
    categoryLabel: "Product Campaign",
    type: "Creative Art Direction & Photography",
    description: "Vibrant product photography and orange juice packaging campaign design for Zesta's Citrus Burst.",
    tag: "Photography",
    image: "images/zesta-juice.jpg",
    icon: "package",
    url: "https://zesta-juice.vercel.app/",
    accentColor: "#F97316"
  },
  {
    id: "port-green-suit",
    title: "Sage Editorial Campaign",
    category: "brand-identity",
    categoryLabel: "Art Direction",
    type: "Editorial Photography & Branding",
    description: "Minimalist fashion photography concept and premium color grading designed for lifestyle apparel.",
    tag: "Creative Direction",
    image: "images/green-suit-model.jpg",
    icon: "sparkles",
    url: "https://nilecollective.co/",
    accentColor: "#15803D"
  },
  {
    id: "port-solva-beverage",
    title: "Solva Beverages Campaign",
    category: "packaging",
    categoryLabel: "Product Photography",
    type: "Creative Packaging & Styling",
    description: "Premium denim pocket-bottle styling and beverage campaign photoshoot for Citrus Sunvale.",
    tag: "Product Shoot",
    image: "images/solva-beverage.jpg",
    icon: "package",
    url: "https://solvabeverages.com/",
    accentColor: "#F59E0B"
  },
  {
    id: "port-nile-africa",
    title: "Nile Africa",
    category: "websites",
    categoryLabel: "Core Infrastructure",
    type: "Core Infrastructure",
    description: "The digital commerce engine designed for African merchants to scale and dominate global markets.",
    tag: "Core Infrastructure",
    gradient: "linear-gradient(135deg, #059669 0%, #064E3B 100%)",
    icon: "globe",
    url: "https://nile.ng",
    accentColor: "#059669"
  },
  {
    id: "port-koinsave",
    title: "Koinsave",
    category: "app-screens",
    categoryLabel: "Fintech",
    type: "Fintech",
    description: "Digital banking and secure savings infrastructure designed for wealth preservation and asset protection.",
    tag: "Fintech",
    gradient: "linear-gradient(135deg, #2563EB 0%, #1E3A8A 100%)",
    icon: "trending-up",
    url: "https://koinsave.co/",
    accentColor: "#2563EB"
  },
  {
    id: "port-greenlife-pharma",
    title: "Greenlife Pharmaceuticals",
    category: "websites",
    categoryLabel: "Enterprise Healthcare",
    type: "Healthcare",
    description: "Stabilized high-stakes healthcare commerce portal for Greenlife, one of Africa's largest pharmaceutical companies.",
    tag: "Healthcare Portal",
    gradient: "linear-gradient(135deg, #10B981 0%, #064E3B 100%)",
    icon: "globe",
    url: "https://greenlifepharmaceuticals.com/",
    accentColor: "#10B981"
  },
  {
    id: "port-dbd-shoot",
    title: "Day By Day Wellness Campaign",
    category: "packaging",
    categoryLabel: "Product Photography",
    type: "Creative Shoot & Art Direction",
    description: "Funky and bold product photography campaign designed for Day By Day supplement lines.",
    tag: "Art Direction",
    image: "images/greenlife-product-2.jpg",
    icon: "package",
    url: "https://dbdgreenlife.vercel.app/",
    accentColor: "#D946EF"
  },
  {
    id: "port-dbd-packaging",
    title: "Day By Day Wellness Packaging",
    category: "packaging",
    categoryLabel: "Packaging & Showcase",
    type: "Product Showcase",
    description: "Premium product presentation and packaging shoot for supplement containers.",
    tag: "Product Design",
    image: "images/greenlife-product-1.jpg",
    icon: "package",
    url: "https://dbdgreenlife.vercel.app/",
    accentColor: "#A21CAF"
  },
  {
    id: "port-dbd-website",
    title: "Day By Day Wellness Store",
    category: "websites",
    categoryLabel: "Web storefront",
    type: "Custom Web Store",
    description: "A gorgeous, responsive custom web storefront designed for Day By Day Wellness products.",
    tag: "E-Commerce",
    gradient: "linear-gradient(135deg, #8B5CF6 0%, #5B21B6 100%)",
    icon: "globe",
    url: "https://dbdgreenlife.vercel.app/",
    accentColor: "#8B5CF6"
  },
  {
    id: "port-bugawheels",
    title: "Buga Wheels",
    category: "app-screens",
    categoryLabel: "Mobility",
    type: "Mobility",
    description: "Scalable car rental platform featuring automated bookings, customer checkouts, and custom admin portals.",
    tag: "Mobility",
    gradient: "linear-gradient(135deg, #F59E0B 0%, #78350F 100%)",
    icon: "phone",
    url: "https://bugawheels.com/",
    accentColor: "#F59E0B"
  },
  {
    id: "port-olaide-ngo",
    title: "Olaide Faith Foundation",
    category: "websites",
    categoryLabel: "NGO Web System",
    type: "NGO Website",
    description: "Sleek, responsive web portal for Olaide Faith Global Foundation, driving donation campaigns and community updates.",
    tag: "NGO / Community",
    gradient: "linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)",
    icon: "globe",
    url: "https://www.olaidefaithglobalfoundation.org/",
    accentColor: "#3B82F6"
  },
  {
    id: "port-nilecollective",
    title: "Nile Collective",
    category: "brand-identity",
    categoryLabel: "Ecosystem",
    type: "Ecosystem",
    description: "A hub and design system for high-growth commerce entities built under Nile Africa's umbrella.",
    tag: "Ecosystem",
    gradient: "linear-gradient(135deg, #4F46E5 0%, #312E81 100%)",
    icon: "sparkles",
    url: "https://nilecollective.co/",
    accentColor: "#4F46E5"
  },
  {
    id: "port-nilebooking",
    title: "Nile Booking",
    category: "websites",
    categoryLabel: "SaaS",
    type: "SaaS",
    description: "Automated booking and scheduling system for fast-growing service businesses.",
    tag: "SaaS",
    gradient: "linear-gradient(135deg, #0D9488 0%, #115E59 100%)",
    icon: "globe",
    url: "https://nilebooking.co/",
    accentColor: "#0D9488"
  },
  {
    id: "port-linknest",
    title: "LinkNest",
    category: "brand-identity",
    categoryLabel: "Productivity",
    type: "Productivity",
    description: "High-performance dynamic bio-link and micro-landing page infrastructure for creators and brands.",
    tag: "Productivity",
    gradient: "linear-gradient(135deg, #EC4899 0%, #9D174D 100%)",
    icon: "sparkles",
    url: "https://mylinknest.com/",
    accentColor: "#EC4899"
  },
  {
    id: "port-dmxlogistics",
    title: "DMX Logistics",
    category: "websites",
    categoryLabel: "Logistics",
    type: "Logistics",
    description: "Custom operational dashboard and route dispatch automation for 100M+ MRR logistics systems.",
    tag: "Logistics",
    gradient: "linear-gradient(135deg, #EF4444 0%, #7F1D1D 100%)",
    icon: "package",
    url: "https://mydmx.ng/",
    accentColor: "#EF4444"
  },
  {
    id: "port-nubanclabs",
    title: "Nubanc Labs",
    category: "app-screens",
    categoryLabel: "R&D",
    type: "R&D",
    description: "Experimental sandbox environment for next-generation digital banking research and smart transaction trials.",
    tag: "R&D",
    gradient: "linear-gradient(135deg, #6366F1 0%, #312E81 100%)",
    icon: "phone",
    url: "https://www.nubanclabs.com/",
    accentColor: "#6366F1"
  },
  {
    id: "port-fashiontally",
    title: "FashionTally",
    category: "app-screens",
    categoryLabel: "Fashion ERP",
    type: "Fashion ERP",
    description: "The core operating system designed for managing manufacturing, order processing, and apparel scale.",
    tag: "Fashion ERP",
    gradient: "linear-gradient(135deg, #8B5CF6 0%, #4C1D95 100%)",
    icon: "package",
    url: "https://fashiontally.com/",
    accentColor: "#8B5CF6"
  },
  {
    id: "port-pacificholdings",
    title: "Pacific Holdings",
    category: "websites",
    categoryLabel: "Enterprise Architecture",
    type: "Enterprise Architecture",
    description: "Industrial database integrations and corporate web portals stabilizing operations across sectors.",
    tag: "Enterprise Architecture",
    gradient: "linear-gradient(135deg, #374151 0%, #111827 100%)",
    icon: "globe",
    url: "https://pacificholdingsltd.com/",
    accentColor: "#374151"
  }
];
